language: node_js
node_js:
  - "8"
dist: trusty
sudo: false
git:
  depth: 1
cache:
  directories:
    - "node_modules"
    - "$HOME/.npm"
install:
  - npm run install:all
script:
  - npm run build
notifications:
  email:
    recipients:
      - alexperezdev@gmail.com